spring:
  datasource:
    url: jdbc:mysql://globalstudents-db.cftlev9uds9u.ap-northeast-2.rds.amazonaws.com:3306/globalstudentsdb
    username: root
    password: globalstudents
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false