spring:
  datasource:
    url: jdbc:mysql://globalstudents-db.cftlev9uds9u.ap-northeast-2.rds.amazonaws.com:3306/globalstudentsdb
    username: root
    password: globalstudents
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: globalstudentsumc@gmail.com
    password: qqwdwenysrmchgxp

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: globalstudents-redis.0q8fma.ng.0001.apn2.cache.amazonaws.com
    port: 6379

  jwt:
    secret: qwertyoasdfqwerldfkknjvldmocimdonivosfinvifnodocvifnoinoifdnovinodoi

  cloud:
    aws:
      s3:
        bucket: global-students
      credentials:
        access-key: AKIAWQTWEXHUJ5K5QLVP
        secret-key: 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
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false